### ISSUE TITLE
Fast solution to reject broken shares?

### ISSUE THREAD

**Issue by Blitss** [Snipa22/xmr-node-proxy#126]
Hi,
Is there any way to reject bad shares (which are not v7 shares) like supportxmr do? It returns:
`{"code":-1,"message":"Incorrect hashing protocol in use. Please upgrade/fix your miner"})`

Thanks.

**Comment by jaboweb** [comment]
fixed in b6cb5a999a42a2705200275e22e967bc0bd8bc32

**Comment by Blitss** [comment]
@jaboweb but I still receiving "accepted" messages from xmrig v2.4
I expect proxy to reject such shares.

**Comment by Snipa22** [comment]
SupportXMR uses a private branch of the code base, I detect bad shares, and validate them as Variant 0, and if they are, then I can confirm that they're old, and tag/flag as such.
